### TEST WebSocket Request
WEBSOCKET ws://localhost:9010/ws
Content-Type: application/json

[2, "custom-001", "StartTransaction", {
    "idTag": "fail-member-uuid-001",
    "transactionId": "transaction-001"
}]
===

###

#[2, "custom-001", "StartTransaction", {
#    "idTag": "member-uuid-001",
#    "transactionId": "transaction-001"
#}]

#[2, "custom-001", "MeterValue", {
#      "meterValueAmount": 112.30,
#      "transactionId": "transaction-001"
#}]

#[2, "custom-001", "StopTransaction", {
#    "transactionId": "transaction-001",
#    "idTag": "member-uuid-001"
#    "meterValueAmount": 0.00
#}]
