### TEST WebSocket Request
WEBSOCKET ws://localhost:9010/ws
Content-Type: application/json

[2, "custom-001", "StopTransaction", {
      "transactionId": "test-001",
      "chargingAmount": 10.10
}]
###